# Generated by Django 3.0.3 on 2021-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=10)),
                ('location', models.CharField(default='', max_length=10)),
                ('is_liked', models.BooleanField(default=0)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
